package Web_Drink_Store.webstore.service.impl;
import Web_Drink_Store.webstore.dto.cart.*; import Web_Drink_Store.webstore.entity.*; import Web_Drink_Store.webstore.enums.ProductStatus; import Web_Drink_Store.webstore.exception.*; import Web_Drink_Store.webstore.repository.*; import Web_Drink_Store.webstore.service.CartService; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.BigDecimal; import java.util.*;
@Service
public class CartServiceImpl implements CartService {
    private final CartRepository carts; private final CartItemRepository items; private final ProductRepository products; private final UserRepository users;
    public CartServiceImpl(CartRepository c,CartItemRepository i,ProductRepository p,UserRepository u){carts=c;items=i;products=p;users=u;}
    private Cart cart(Long userId){return carts.findByUserId(userId).orElseGet(() -> {User u=users.findById(userId).orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy user")); Cart c=new Cart();c.setUser(u);return carts.save(c);});}
    private CartResponse map(Cart c){List<CartItemResponse> rs=items.findByCartId(c.getId()).stream().map(i->{BigDecimal total=i.getProduct().getPrice().multiply(BigDecimal.valueOf(i.getQuantity())); return new CartItemResponse(i.getId(),i.getProduct().getId(),i.getProduct().getName(),i.getProduct().getPrice(),i.getQuantity(),total);}).toList(); BigDecimal total=rs.stream().map(CartItemResponse::getLineTotal).reduce(BigDecimal.ZERO,BigDecimal::add); return new CartResponse(c.getId(),rs,total);}
    public CartResponse getCart(Long userId){return map(cart(userId));}
    @Transactional public CartResponse addItem(Long userId,CartItemRequest r){if(r.getQuantity()==null||r.getQuantity()<=0)throw new BadRequestException("Số lượng phải > 0"); Cart c=cart(userId); Product p=products.findById(r.getProductId()).orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy product")); if(p.getStatus()!=ProductStatus.ACTIVE)throw new BadRequestException("Sản phẩm không hoạt động"); CartItem item=items.findByCartIdAndProductId(c.getId(),p.getId()).orElseGet(CartItem::new); int qty=item.getId()==null?r.getQuantity():item.getQuantity()+r.getQuantity(); if(qty>p.getStockQuantity())throw new BadRequestException("Vượt quá tồn kho"); item.setCart(c);item.setProduct(p);item.setQuantity(qty);items.save(item);return map(c);}
    public CartResponse updateItem(Long userId,Long itemId,Integer quantity){if(quantity==null||quantity<=0)throw new BadRequestException("Số lượng phải > 0"); Cart c=cart(userId); CartItem i=items.findById(itemId).orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy cart item")); if(!i.getCart().getId().equals(c.getId()))throw new UnauthorizedException("Không có quyền"); if(quantity>i.getProduct().getStockQuantity())throw new BadRequestException("Vượt quá tồn kho");i.setQuantity(quantity);items.save(i);return map(c);}
    public CartResponse removeItem(Long userId,Long itemId){Cart c=cart(userId);CartItem i=items.findById(itemId).orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy cart item"));if(!i.getCart().getId().equals(c.getId()))throw new UnauthorizedException("Không có quyền");items.delete(i);return map(c);}
    @Transactional public void clear(Long userId){items.deleteByCartId(cart(userId).getId());}
}
