package Web_Drink_Store.webstore.service.impl;
import Web_Drink_Store.webstore.dto.order.*; import Web_Drink_Store.webstore.entity.*; import Web_Drink_Store.webstore.enums.*; import Web_Drink_Store.webstore.exception.*; import Web_Drink_Store.webstore.repository.*; import Web_Drink_Store.webstore.service.OrderService; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.LocalDateTime; import java.util.*;
@Service
public class OrderServiceImpl implements OrderService {
    private final OrderRepository orders; private final OrderItemRepository orderItems; private final UserRepository users; private final AddressRepository addresses; private final CartRepository carts; private final CartItemRepository cartItems; private final ProductRepository products; private final PromotionRepository promotions;
    public OrderServiceImpl(OrderRepository o,OrderItemRepository oi,UserRepository u,AddressRepository a,CartRepository c,CartItemRepository ci,ProductRepository p,PromotionRepository pr){orders=o;orderItems=oi;users=u;addresses=a;carts=c;cartItems=ci;products=p;promotions=pr;}
    @Transactional public OrderResponse create(Long userId,OrderRequest r){User u=users.findById(userId).orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy user")); Address a=addresses.findById(r.getAddressId()).orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy địa chỉ")); if(!a.getUser().getId().equals(userId))throw new UnauthorizedException("Địa chỉ không thuộc user"); Cart c=carts.findByUserId(userId).orElseThrow(() -> new BadRequestException("Giỏ hàng trống")); List<CartItem> cis=cartItems.findByCartId(c.getId()); if(cis.isEmpty())throw new BadRequestException("Giỏ hàng trống");
        BigDecimal subtotal=BigDecimal.ZERO; for(CartItem ci:cis){Product p=ci.getProduct(); if(p.getStatus()!=ProductStatus.ACTIVE||ci.getQuantity()>p.getStockQuantity())throw new BadRequestException("Sản phẩm "+p.getName()+" không đủ hàng"); subtotal=subtotal.add(p.getPrice().multiply(BigDecimal.valueOf(ci.getQuantity())));}
        Promotion promotion=null; BigDecimal discount=BigDecimal.ZERO; if(r.getPromotionCode()!=null&&!r.getPromotionCode().isBlank()){promotion=promotions.findByCode(r.getPromotionCode().trim()).orElseThrow(() -> new BadRequestException("Mã khuyến mãi không hợp lệ")); LocalDateTime now=LocalDateTime.now(); if(promotion.getStatus()!=PromotionStatus.ACTIVE||(promotion.getStartAt()!=null&&now.isBefore(promotion.getStartAt()))||(promotion.getEndAt()!=null&&now.isAfter(promotion.getEndAt())))throw new BadRequestException("Khuyến mãi không còn hiệu lực"); if(promotion.getMinOrderValue()!=null&&subtotal.compareTo(promotion.getMinOrderValue())<0)throw new BadRequestException("Chưa đạt giá trị đơn tối thiểu"); if(promotion.getDiscountType()==DiscountType.PERCENT){discount=subtotal.multiply(promotion.getDiscountValue()).divide(BigDecimal.valueOf(100),2,RoundingMode.HALF_UP);}else{discount=promotion.getDiscountValue();} if(promotion.getMaxDiscountValue()!=null&&discount.compareTo(promotion.getMaxDiscountValue())>0)discount=promotion.getMaxDiscountValue(); if(discount.compareTo(subtotal)>0)discount=subtotal;}
        Order o=new Order();o.setUser(u);o.setAddress(a);o.setPromotion(promotion);o.setStatus(OrderStatus.PENDING);o.setSubtotal(subtotal);o.setDiscountAmount(discount);o.setTotalAmount(subtotal.subtract(discount));orders.save(o);
        for(CartItem ci:cis){Product p=ci.getProduct(); OrderItem oi=new OrderItem();oi.setOrder(o);oi.setProduct(p);oi.setQuantity(ci.getQuantity());oi.setUnitPrice(p.getPrice());oi.setLineTotal(p.getPrice().multiply(BigDecimal.valueOf(ci.getQuantity())));orderItems.save(oi);p.setStockQuantity(p.getStockQuantity()-ci.getQuantity());products.save(p);} cartItems.deleteByCartId(c.getId()); return map(o);
    }
    public List<OrderResponse> getMyOrders(Long userId){return orders.findByUserIdOrderByCreatedAtDesc(userId).stream().map(this::map).toList();}
    public List<OrderResponse> getAll(){return orders.findAll().stream().map(this::map).toList();}
    public OrderResponse updateStatus(Long id,OrderStatus status){Order o=orders.findById(id).orElseThrow(() -> new ResourceNotFoundException("Không tìm thấy order"));o.setStatus(status);return map(orders.save(o));}
    private OrderResponse map(Order o){List<OrderItemResponse> its=orderItems.findByOrderId(o.getId()).stream().map(i->new OrderItemResponse(i.getProduct().getId(),i.getProduct().getName(),i.getQuantity(),i.getUnitPrice(),i.getLineTotal())).toList();return new OrderResponse(o.getId(),o.getStatus(),o.getSubtotal(),o.getDiscountAmount(),o.getTotalAmount(),o.getCreatedAt(),its);}
}
